---
- name: Write facts into a csv file
  hosts: juniper
  gather_facts: false
  tasks:
  - name: get facts
    napalm_get_facts:
      filter: facts,lldp_neighbors_detail
    register: test

  - name: copy facts to txt
    copy:
      dest: /home/nstadmin/nxui-ansible/nxui-juniper/lldpfacts.txt
      content: "{{ test.ansible_facts.napalm_lldp_neighbors_detail}}"
      #[item][0]['parent_interface'] }},{{ test.ansible_facts.napalm_lldp_neighbors_detail[item][0]['remote_chassis_id'] }}
    #with_items: "{{ test.ansible_facts.napalm_lldp_neighbors_detail.keys() }}"
    delegate_to: localhost

  #- name: CSV - Blank lines removal
    #lineinfile:
      #path: "./{{ output_path }}/{{ filename }}"
      #state: absent
      #regex: '^\s*$'

     