---
- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Get facts
      napalm_get_facts:
        filter: facts,lldp_neighbors_detail
      register: test
      
    #- name: print result
      #debug:
        #msg: "{{test}}"

    #- name: save serial to csv
      #copy:
        #content: "{{ test.ansible_facts.napalm_facts.serial_number }}"
        #dest: /home/nstadmin/nxui-ansible/nxui-juniper/serial.csv

    - name: copy facts to csv
      copy: 
        content: "{{test.ansible_facts.napalm_facts.fqdn}},\n {{ansible_host}},\n"
        #{{ test.ansible_facts.napalm_lldp_neighbors_detail[item] }},\n"
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
      #with_items: "{{ test.ansible_facts.napalm_lldp_neighbors_detail.keys()}}"
      delegate_to: localhost
    
    - name: print lldp
      debug:
        msg: "{{test.ansible_facts.napalm_lldp_neighbors_detail}}"

    #- name: copy lldp facts
      #lineinfile:
        #insertafter: EOF
        #dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
        #line: "{{ test.ansible_facts.napalm_lldp_neighbors_detail[item] }}\n"
      #with_items: 
       #- "{{ test.ansible_facts.napalm_lldp_neighbors_detail.keys() }}"

    #- name: Print each switch/port
      #debug:
        #msg: "{{ test.ansible_facts.napalm_lldp_neighbors_detail[item] }}"
      #with_items: "{{ test.ansible_facts.napalm_lldp_neighbors_detail.keys() }}"

    - name: copy lldp facts
      lineinfile:
        insertafter: EOF
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
        line: "{{ test.ansible_facts.napalm_lldp_neighbors_detail['ge-0/0/19'][1] }}\n"
      #with_items: 
       #- "{{ test.ansible_facts.napalm_lldp_neighbors_detail.keys() }}"