---
- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
    #- name: Retrieve get_facts, get_lldp
      #napalm_get_facts:
         #filter: facts,lldp_neighbors_detail
    #- debug:
        #var: napalm_facts

    - name: Print all available facts
      napalm_get_facts:
      
    - debug:
        var: napalm_facts
        msg: "{{napalm_facts}}"
    #- local_action: 
        #module: copy 
        #content: "{{ ansible_facts.napalm_lldp_neighbors_detail}},"
        #dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
    #- name: "copy ip"
      #copy: 
        #content: "{{ ansible_host }},"
        #dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
    
    #- debug:
        #msg: "{{ansible_facts.napalm_facts.napalm_lldp_neighbors_detail}}"
      #with_items: "{{ lldp.keys() }}"

    #- name: "copy facts to csv"
      #copy: 
        #content: "{{napalm_facts.fqdn}},\n {{ansible_host}},\n {{ansible_facts.napalm_lldp_neighbors_detail}}\n "
        #dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
      #delegate_to: localhost
   


    #- name: Print each switch/port
      #debug:
        #msg: "{{ ansible_facts.napalm_lldp_neighbors_detail[item][remote_chassis_id] }}"
      #with_items: "{{ ansible_facts.napalm_lldp_neighbors_detail.keys() }}"



