---
- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Retrieve get_facts, get_lldp
      napalm_get_facts:
         filter: facts,lldp_neighbors_detail
    - debug:
        var: napalm_facts

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    #- local_action: 
        #module: copy 
        #content: "{{ ansible_facts.napalm_lldp_neighbors_detail}},"
        #dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
    #- name: "copy ip"
      #copy: 
        #content: "{{ ansible_host }},"
        #dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
    
    #- debug:
        #msg: "{{ansible_facts.napalm_lldp_neighbors_detail[0]}}"
      #with_items: "{{ lldp.keys() }}"

    - name: "copy facts to csv"
      copy: 
        content: "{{napalm_facts.fqdn}},\n {{ansible_host}},\n {{ansible_facts.napalm_lldp_neighbors_detail}}\n "
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
      delegate_to: localhost
   
    - name: Gather information from lldp
      lldp:

    - name: Print each switch/port
      debug:
        msg: "{{ lldp[item]['chassis']['name'] }} / {{ lldp[item]['port']['ifname'] }}"
      with_items: "{{ lldp.keys() }}"


