---
- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:

    - name: Retrieve get_facts, get_lldp
      napalm_get_facts:
        filter: facts,lldp_neighbors_detail
    - debug:
        var: napalm_facts

    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - local_action: 
        module: copy 
        content: "{{ ansible_facts }}"
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
    - local_action: 
        module: copy 
        content: "{{ ansible_host }}"
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/hostip.txt
    
    - debug:
        msg: "{{napalm_facts.fqdn}}"

    - name: "copy fqdn"
      copy: 
        content: "{{napalm_facts.fqdn}}"
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/fqdn.txt
      delegate_to: localhost

