---
- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Print all available facts
      napalm_get_facts:
        filter: facts,lldp_neighbors_detail
      register: test
      
    - name: print result
      debug:
        msg: "{{test}}"

    #- name: save serial to csv
      #copy:
        #content: "{{ test.ansible_facts.napalm_facts.serial_number }}"
        #dest: /home/nstadmin/nxui-ansible/nxui-juniper/serial.csv

    - name: "copy facts to csv"
      copy: 
        content: "{{test.ansible_facts.napalm_facts.fqdn}},\n {{ansible_host}},\n {{test.ansible_facts.napalm_facts.napalm_lldp_neighbors_detail}} "
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
      delegate_to: localhost

   


    #- name: Print each switch/port
      #debug:
        #msg: "{{ ansible_facts.napalm_lldp_neighbors_detail[item][remote_chassis_id] }}"
      #with_items: "{{ ansible_facts.napalm_lldp_neighbors_detail.keys() }}"



