---
- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Get facts
      napalm_get_facts:
        filter: facts,lldp_neighbors_detail
      register: test
    - name: print lldp
      debug:
        msg: "{{test.ansible_facts.napalm_lldp_neighbors_detail}}"

    - name: copy facts to csv 
      copy:
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.csv
        content: "{{test.ansible_facts.napalm_facts.fqdn}},{{ansible_host}}"
      #with_items: "{{ test.ansible_facts.napalm_lldp_neighbors_detail.keys() }}"
      delegate_to: localhost
    - name: copy facts to txt
      copy:
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/lldpfacts.txt
        content: "{{ test.ansible_facts.napalm_lldp_neighbors_detail}}"

