---

- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Retrieve get_facts
      napalm_get_facts:
        filter: facts,lldp_neighbors_detail
    - debug:
        var: napalm_facts

    - name: Print all available facts
      ansible.builtin.debug:
          var: ansible_facts
          msg: "{{ ansible_ssh_host }}"

          
