---

- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Retrieve get_facts
      napalm_get_facts:
        filter: facts,lldp_neighbors_detail
    - debug:
        var: napalm_facts
    - name: print ansible_facts
    - debug:
        var: ansible_facts["kernal"]
    - name: Copy ansible facts to a file.
      copy:
      content: "{{ ansible_facts }}"
      dest: /getfacts.txt
