---

- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Retrieve get_facts, get_interfaces
      napalm_get_facts:
        filter: facts,interfaces,lldp_neighbors_detail
    - debug:
        var: napalm_facts

    ##- name: Print all available facts
      ##ansible.builtin.debug:
        ##  var: ansible_facts
