---

- name: napalm 
  hosts: juniper
  gather_facts: False
  tasks:
   - name: Retrieve get_facts
      napalm_get_facts:
        filter: facts,lldp_neighbors_detail
   - debug:
        var: napalm_facts
   - name: print ansible_facts
   - ansible.builtin.debug:
        var: ansible_facts

   - name: Copy ansible facts to a file.
   - copy:
        content: ansible_facts 
        dest: /home/nstadmin/nxui-ansible/nxui-juniper/getfacts.txt

    ##- name: Print all available facts
     ##ansible.builtin.debug:
      ##  var: ansible_facts
